//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiZFormMain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_choices
    {
        public int Id { get; set; }
        public int QuestionID { get; set; }
        public bool IsCorrect { get; set; }
        public string Choice { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
