//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiZFormMain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Questions_answer
    {
        public int UserID { get; set; }
        public int QuestionID { get; set; }
        public bool IsRight { get; set; }
        public System.DateTime Date { get; set; }
        public string ID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
